from car import Car, ElectricCar

car_1 = Car("John", "Honda", "Civic", '2013')
tesla = ElectricCar("Mark", "Honda", "Accord", '2006')
# car_3 = Car("Venki", "Honda", "SUV", '2017')

car_1.car_description()
car_1.odo_reading()
car_1.update_ode(20)
car_1.odo_reading()
car_1.increment_ode(23)
car_1.update_ode(15)
car_1.odo_reading()
car_1.increment_ode(23)
car_1.odo_reading()
car_1.fill_gas_tank(10)
print()

tesla.car_description()
tesla.odo_reading()
tesla.update_ode(20)
tesla.odo_reading()
tesla.increment_ode(3)
tesla.update_ode(15)
tesla.odo_reading()
tesla.increment_ode(23)
tesla.odo_reading()
tesla.battery.describe_battery()
tesla.fill_gas_tank()
tesla.battery.get_range()
tesla.battery.upgrade_battery()
tesla.battery.get_range()
